### ISSUE TITLE
IE Driver is not found

### ISSUE THREAD

**Issue by fergusonna** [conductor-framework/conductor#14]
The test is unable to find the iedriver downloaded from the wiki. 

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
16:27:06.480 [main] FATAL io.ddavison.conductor.Locomotive - iedriver not found. See https://github.com/ddavison/getting-started-with-selenium-framework/wiki/WebDriver-Executables for more information.

Process finished with exit code 1
Empty test suite.

Location in the project:
![image](https://cloud.githubusercontent.com/assets/6790737/16394629/33a37a92-3c84-11e6-9efb-59c1879e1640.png)

**Comment by ddavison** [comment]
hey @fergusonna i noticed you closed this.  did you figure everything out?

**Comment by fergusonna** [comment]
Yes, sorry. After I posted this I realized that I had the wrong version number in the Maven dependency.

**Comment by ddavison** [comment]
perfect.  glad you figured it out 👍
