### ISSUE TITLE
FATAL error. 

### ISSUE THREAD

**Issue by underwch** [conductor-framework/conductor#21]
I continue to receive this error:
16:08:40.164 [main] FATAL io.ddavison.conductor.Locomotive - Also see https://github.com/conductor-framework/conductor/wiki/WebDriver-Executables

Process finished with exit code 1

I have my dependencies as follows
` <dependencies>
        <dependency>
            <groupId>io.ddavison</groupId>
            <artifactId>conductor</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.0.1</version>
        </dependency>`

**Comment by ddavison** [comment]
what browser are you trying to use?  if you are using Chrome, you need to have chromedriver executable in the project root

**Comment by underwch** [comment]
I'm using Chrome. I have the chromedriver executable in the project root.

**Comment by underwch** [comment]
Chrome driver executable needed to be updated as google chrome has been updated. Fixed issue.
