### ISSUE TITLE
Long Press/Mouse Down

### ISSUE THREAD

**Issue by lbarbula** [conductor-framework/conductor#24]
Hello! I was wondering if there is an equivalent to mouse up and mouse down? I am trying to simulate a long press of an item and find the simple click handler to not be sufficient. Thanks in advance for your time!

**Comment by ddavison** [comment]
hi there!

in this case, you'd have to utilize the `Actions` API from Selenium.

```java
Actions actions = new Actions(driver);
actions.moveToElement(element).build().perform();
```

that right there does a "long mouse down"

that should work for you!
