### ISSUE TITLE
add selectOptionByIndex

### ISSUE THREAD

**Issue by TheParad0X** [conductor-framework/conductor#25]
Hello,

selectOptionByIndex would be a very useful addition. The drawback with "selectOptionByText" is that one needs to know the exact text to choose. "selectOptionByIndex(1)" could be copy / pasted, which is quite handy.

Cheers from Germany

PS: Also there is a typo on this page: http://conductor.ddavison.io/get-started/ : "At it’s heart" should be "At its heart". And the maven version on this page is not the latest

**Comment by ddavison** [comment]
site also fixed. apologies took so long.  migrated hosts a while back and didn't get a chance to set up my CI. now it's in place ;)
