### ISSUE TITLE
Headless testing

### ISSUE THREAD

**Issue by dbclkclk** [conductor-framework/conductor#6]
Does this work with headless webdrivers?

**Comment by ddavison** [comment]
phantomjs is in there, yea :) if there is something missing, feel free to open a pull request

**Comment by dbclkclk** [comment]
Thanks

**Comment by dbclkclk** [comment]
@ddavison Can I set the @config annotation per environment? Example, on my dev environment, I'm running Chrome but, on my QA environment, I'll be using PhantomJs. 

Thanks again.

**Comment by ddavison** [comment]
if you are using 2.0.* you can use the `CONDUCTOR_BROWSER` environment variable, or implement a more custom solution to account for your different environments

**Comment by makeitright** [comment]
are you really dean?
