### ISSUE TITLE
Using Browser.SAFARI

### ISSUE THREAD

**Issue by svenport** [conductor-framework/conductor#8]
Hello,

first of all: thanks for this smart Selenium hop on. 
I tried to use your framework but stumbled over the following configuration

@Config(browser = Browser.SAFARI, url = "THE URL")

When I tried to run the selenium test, I got the following error:

[main] FATAL io.ddavison.conductor.Locomotive - safaridriver not found. See https://github.com/ddavison/conductor/wiki/WebDriver-Executables for more information.

On the suggested page, only the Chrome WebDriver Executable is described. 

=> Does this mean: Only Chrome is supported yet?
=> How to use any other browser, defined as constant within the class Browser, like Browser.SAFARI?

Thanks in advance for any hints and information.

**Comment by ddavison** [comment]
any browser inside the Browser enumeration is supported, but only chrome has been extensively tested. 

to be honest, you actually pointed out an actual bug with conductor. I hadn't had the chance to even fiddle with safaridriver, and the code forces the test to quit even if you have safaridriver available. 

ill have to fix this later. thanks so much for logging this bug! or, if you're up to it. create a pull request :).

**Comment by ddavison** [comment]
this was fixed in the latest release `2.2.2`

**Comment by Saidkossouri** [comment]
Hello, i have the same issue with IE. Is the issue has been résolved also for IE in that version (2.2.2) ?

Thanks in advance  for any information.

**Comment by ddavison** [comment]
IE driver is supported - https://github.com/conductor-framework/conductor/wiki/WebDriver-Executables#iedriver

**Comment by sk1984** [comment]
Hey is there a way to specify multiple browser in the @Config?
something like, @Config(browser = Browser.SAFARi, Browser.Firefox.....

**Comment by supernevi** [comment]
unfortunately currently not. i solved this by a special way of using testsuites in combining with changing the config by the jvm-env:

System.setProperty(Constants.JVM_CONDUCTOR_BROWSER, Browser.SAFARI.name());
