### ISSUE TITLE
Chrome window running in background and not maximized

### ISSUE THREAD

**Issue by ksadowski** [conductor-framework/conductor#9]
Hey, 

I'm following yours tutorial from here: https://www.airpair.com/selenium/posts/selenium-tutorial-with-java
and have a question:

Does Conductor support running tests in maximized Chrome browser shown on top of other windows? I start test from IntelliJ, can see in OSX dock that browser is opened but it's not on top, so I can't see how test is going (would be nice to see it during test creation). How can I enable this?

**Comment by ddavison** [comment]
this is actually a limit of OSX, not conductor. I know that when I moved from Windows to OSX, that was one of my major annoyances.

you just get used to clicking the window in the dock.  sorry! I agree it's annoying that OSX does this.
